---
title: "DataFest GPS"
author: "Fengling Hu"
date: "3/30/2019"
output: html_document
---
```{r}
library(tidyverse)
library(mosaic)
library(gganimate)
library(randomForest)

total <- read_csv("gameday.csv")[, -1]
gpsFrames <- read_csv("gps.csv")
gps <- read_csv("gps_process.csv")[, -1]
games <- read_csv("gamesWeather.csv")
joined2 = read_csv("joinedAllYesterday.csv")[, -1]

joined2 <- joined2 %>% mutate(SprintDist = round(SprintDist, 2),
                              RunDist = round(RunDist, 2),
                              WalkDist = round(WalkDist, 2),
                              Dist = round(Dist, 1)
)
```

```{r}
gps <- gps %>% left_join(games)
gps <- gps %>% 
    select(-Tournament, -TournamentGame, -Team, -Opponent) %>% 
    rename(DateTrained = Date)
gps$PlayerID <- as.factor(gps$PlayerID)

gps2 <- gps %>% 
    group_by(PlayerID, DateTrained) %>% 
    summarize(SprintDist = sum(Sprintdist),
              RunDist = sum(Rundist),
              WalkDist = sum(Walkdist),
              Dist = sum(distance),
              Outcome = first(Outcome),
              TeamPoints = sum(TeamPoints),
              TeamPointsAllowed = sum(TeamPointsAllowed),
              T_High = first(T_High),
              T_Low = first(T_Low),
              Humidity = first(Humidity),
              Pressure = first(Pressure),
              WindSpeed = first(WindSpeed)
    )

gps2 <- gps2 %>% mutate(SprintDist = round(SprintDist, 2),
                        RunDist = round(RunDist, 2),
                        WalkDist = round(WalkDist, 2),
                        Dist = round(Dist, 1)
)

joined2$PlayerID <- as.factor(joined2$PlayerID)
joined <- joined2 %>% left_join(gps2, by = c("PlayerID", "DateTrained", "SprintDist"), suffix = c("", "y"))

joined <- joined %>% 
    select(-Date, -PlayerID, -Soreness, -Desire, -Irritability, -SleepQuality, -DateTrained, -Sessions) %>% 
    mutate(Outcome = ifelse(Outcome == "W", 1, 
                            ifelse(Outcome == "L", 0, NA)
    ))

joined <- joined[, -(25:30)]
joined <- joined %>% 
    select(Fatigue, MonitoringScore, Exhaustion, everything())

write.csv(joined, "joinedWeather.csv")
```

```{r}
joined <- read_csv("joinedAllYesterday.csv")
training <- joined[is.na(joined$SprintDist), -c(1:3, 5:7, 9, 18:19, 27:33)]
training <- training %>% select(Fatigue, MonitoringScore, Exhaustion, everything())
gameday <- joined[!is.na(joined$SprintDist), ]

write.csv(training, "training.csv")
write.csv(gameday, "gameday.csv")

gamedayDat <- gameday[, c(16, 7, 10:15, 19:25, 26:32)]
```

```{r}
trainingDat <- training[, -c(1, 2)]
rf <- randomForest(Exhaustion ~ . - TrainingReadiness - Fatigue - MonitoringScore, training,
                   na.action = na.omit,
                   ntree = 500,
                   importance = TRUE)
rf
varImpPlot(rf)

trainingDat <- training[, -c(2, 3)]
rf2 <- randomForest(Fatigue ~ . - TrainingReadiness - Exhaustion - MonitoringScore, training,
                    na.action = na.omit,
                    ntree = 500,
                    importance = TRUE)
rf2
varImpPlot(rf2)

trainingDat <- training[, -c(1, 3)]
rf3 <- randomForest(MonitoringScore ~ . - Fatigue - Exhaustion - TrainingReadiness, training,
                    na.action = na.omit,
                    ntree = 500,
                    importance = TRUE)
rf3
varImpPlot(rf3)

ggplot(training, aes(MonitoringScore, Exhaustion)) + geom_point()
```

```{r}
lm <- lm(Exhaustion ~ . - MonitoringScore - Fatigue - TrainingReadiness, data = training)
summary(lm)
lm <- lm(Fatigue ~ . - Exhaustion - MonitoringScore - TrainingReadiness, data = training)
summary(lm)
lm <- lm(MonitoringScore ~ . - Exhaustion - Fatigue - TrainingReadiness, data = training)
summary(lm)

rfGame <- randomForest(Exhaustion ~ ., gamedayDat,
                       ntree = 500,
                       importance = TRUE)
rfGame
varImpPlot(rfGame)

lmGame <- lm(Exhaustion ~ ., data = gamedayDat)
summary(lmGame)
```

```{r}
p <- ggplot(gpsFrames %>% filter(GameID == 20, Half == 1)) + 
    geom_point(aes(Latitude, Longitude, color = PlayerID)) +
    transition_time(FrameID) +
    enter_fade() +
    exit_fade()
p
animate(p, fps = 50)

test <- gpsFrames %>% filter(GameID == 20, Half == 1)
test$PlayerID <- as.factor(test$PlayerID)

ggplot(test) + geom_point(aes(Latitude, Longitude, color = as.factor(PlayerID))) + 
    theme_bw() +
    theme(panel.grid = element_blank(),
          panel.border = element_blank()) +
    ylim(-82.34, -82.36)

ggplot(test) + geom_point(aes(Latitude, Longitude, color = PlayerID), size = 1) + 
    theme_bw() +
    theme(panel.grid = element_blank(),
          panel.border = element_blank(),
          plot.title = element_text(hjust = 0.5, size = 15),
          legend.position = "none") +
    ylim(-82.35, -82.348) +
    xlim(48.4425, 48.4435)# +
    labs(title = "Game during Kitakyushu Tournament in Japan")


ggplot(test) + geom_point(aes(Latitude, Longitude, color = PlayerID), size = 1) + 
    theme_bw() +
    theme(panel.grid = element_blank(),
          panel.border = element_blank(),
          plot.title = element_text(hjust = 0.5, size = 15),
          legend.position = "none") +
    ylim(-82.35, -82.348)# +
    labs(title = "Game during Kitakyushu Tournament in Japan")


```

